# Generated by Django 4.2.11 on 2024-05-10 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 22, 37, 18, 223327, tzinfo=datetime.timezone.utc)),
        ),
    ]
