# Generated by Django 4.2.11 on 2024-05-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of the quiz in minutes')),
                ('required_scored_to_pass', models.IntegerField(help_text='required score to pass')),
                ('diffculity', models.CharField(choices=[('easy', 'easy'), ('meduim', 'meduim'), ('hard', 'hard')], max_length=6)),
            ],
        ),
    ]
