# Generated by Django 4.2.11 on 2024-05-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizes',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
