# Generated by Django 4.2.11 on 2024-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quizes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='required_scored_to_pass',
            field=models.IntegerField(help_text='required score in %'),
        ),
    ]
